uploads = []
generated = []

[[outputs]]
id = "OSvNjlPaZ0dc6FSAGpNqX"
uri = "file://nirmal_connect_brochure.zip"
type = "unspecified"
title = "Nirmal Connect – Tamil Client Brochure (HTML)"

[[outputs]]
id = "ug5Mv7IfTfbEVcSrEnWMe"
uri = "file://nirmal_connect_admin_guide.zip"
type = "unspecified"
title = "Nirmal Connect – Admin Feature Guide (Tamil)"

[[outputs]]
id = "7kDlm9kf-jOg9JvNaZ6eW"
uri = "file://nirmal_connect_presentation.zip"
type = "unspecified"
title = "Nirmal Connect – Admin Presentation (Automystics Branded)"

[[outputs]]
id = "Jtpo-QZzbVfb_wb3CmADK"
uri = "file://people_connect_presentation.zip"
type = "unspecified"
title = "People Connect – Admin Presentation (Tamil + English)"

[[outputs]]
id = "Vvc9uSi-JBnpqsauGL6gJ"
uri = "file://people_connect_website_presentation.zip"
type = "unspecified"
title = "People Connect – Website Presentation (Tamil + English)"
