export interface TnConstituency {
  district: string;
  constituency: string;
}

export const TN_CONSTITUENCIES: TnConstituency[] = [
  // Tiruvallur
  { district: "Tiruvallur", constituency: "Gummidipoondi" },
  { district: "Tiruvallur", constituency: "Ponneri" },
  { district: "Tiruvallur", constituency: "Tiruttani" },
  { district: "Tiruvallur", constituency: "Sholavaram" },
  { district: "Tiruvallur", constituency: "Poonamallee" },
  { district: "Tiruvallur", constituency: "Ambattur" },
  { district: "Tiruvallur", constituency: "Maduravoyal" },
  { district: "Tiruvallur", constituency: "Avadi" },
  // Chennai
  { district: "Chennai", constituency: "Harbour" },
  { district: "Chennai", constituency: "Chepauk-Thiruvallikeni" },
  { district: "Chennai", constituency: "Royapuram" },
  { district: "Chennai", constituency: "Kolathur" },
  { district: "Chennai", constituency: "Villivakkam" },
  { district: "Chennai", constituency: "Thiru Vi Ka Nagar" },
  { district: "Chennai", constituency: "Egmore" },
  { district: "Chennai", constituency: "Perambur" },
  { district: "Chennai", constituency: "Dr Radhakrishnan Nagar" },
  { district: "Chennai", constituency: "Periyapalayam" },
  { district: "Chennai", constituency: "Velachery" },
  { district: "Chennai", constituency: "Virugambakkam" },
  { district: "Chennai", constituency: "Saidapet" },
  { district: "Chennai", constituency: "Thousand Lights" },
  { district: "Chennai", constituency: "Anna Nagar" },
  // Kancheepuram
  { district: "Kancheepuram", constituency: "Alandur" },
  { district: "Kancheepuram", constituency: "Sriperumbudur" },
  { district: "Kancheepuram", constituency: "Pallavaram" },
  { district: "Kancheepuram", constituency: "Tambaram" },
  { district: "Kancheepuram", constituency: "Sholinganallur" },
  { district: "Kancheepuram", constituency: "Kancheepuram" },
  { district: "Kancheepuram", constituency: "Uthiramerur" },
  // Chengalpet
  { district: "Chengalpet", constituency: "Chengalpet" },
  { district: "Chengalpet", constituency: "Cheyyur" },
  { district: "Chengalpet", constituency: "Madurantakam" },
  { district: "Chengalpet", constituency: "St. Thomas Mount" },
  { district: "Chengalpet", constituency: "Pallikaranai" },
  { district: "Chengalpet", constituency: "Thiruporur" },
  { district: "Chengalpet", constituency: "Vandavasi" },
  // Vellore
  { district: "Vellore", constituency: "Vellore" },
  { district: "Vellore", constituency: "Anaikattu" },
  { district: "Vellore", constituency: "Katpadi" },
  { district: "Vellore", constituency: "Ranipet" },
  { district: "Vellore", constituency: "Arcot" },
  { district: "Vellore", constituency: "Gudiyatham" },
  // Ranipet
  { district: "Ranipet", constituency: "Arakkonam" },
  { district: "Ranipet", constituency: "Sholinghur" },
  { district: "Ranipet", constituency: "Walajah" },
  { district: "Ranipet", constituency: "Arakonam" },
  { district: "Ranipet", constituency: "Walajapet" },
  // Tirupattur
  { district: "Tirupattur", constituency: "Tirupattur" },
  { district: "Tirupattur", constituency: "Ambur" },
  { district: "Tirupattur", constituency: "Jolarpet" },
  { district: "Tirupattur", constituency: "Vaniyambadi" },
  // Krishnagiri
  { district: "Krishnagiri", constituency: "Krishnagiri" },
  { district: "Krishnagiri", constituency: "Veppanahalli" },
  { district: "Krishnagiri", constituency: "Hosur" },
  { district: "Krishnagiri", constituency: "Uthangarai" },
  { district: "Krishnagiri", constituency: "Bargur" },
  // Dharmapuri
  { district: "Dharmapuri", constituency: "Dharmapuri" },
  { district: "Dharmapuri", constituency: "Palacode" },
  { district: "Dharmapuri", constituency: "Pennagaram" },
  { district: "Dharmapuri", constituency: "Pappireddipatti" },
  // Salem
  { district: "Salem", constituency: "Omalur" },
  { district: "Salem", constituency: "Mettur" },
  { district: "Salem", constituency: "Edappadi" },
  { district: "Salem", constituency: "Salem West" },
  { district: "Salem", constituency: "Salem" },
  { district: "Salem", constituency: "Veerapandi" },
  { district: "Salem", constituency: "Gangavalli" },
  { district: "Salem", constituency: "Attur" },
  { district: "Salem", constituency: "Yercaud" },
  // Namakkal
  { district: "Namakkal", constituency: "Rasipuram" },
  { district: "Namakkal", constituency: "Senthamangalam" },
  { district: "Namakkal", constituency: "Namakkal" },
  { district: "Namakkal", constituency: "Paramathi-Velur" },
  { district: "Namakkal", constituency: "Tiruchengode" },
  // Erode
  { district: "Erode", constituency: "Erode East" },
  { district: "Erode", constituency: "Erode West" },
  { district: "Erode", constituency: "Modakurichi" },
  { district: "Erode", constituency: "Bhavani" },
  { district: "Erode", constituency: "Anthiyur" },
  { district: "Erode", constituency: "Gobichettipalayam" },
  { district: "Erode", constituency: "Bhavanisagar" },
  // Tirupur
  { district: "Tirupur", constituency: "Avanashi" },
  { district: "Tirupur", constituency: "Tirupur North" },
  { district: "Tirupur", constituency: "Tirupur South" },
  { district: "Tirupur", constituency: "Palladam" },
  { district: "Tirupur", constituency: "Dharapuram" },
  { district: "Tirupur", constituency: "Kangayam" },
  { district: "Tirupur", constituency: "Udumalpet" },
  // Coimbatore
  { district: "Coimbatore", constituency: "Pollachi" },
  { district: "Coimbatore", constituency: "Anaimalai" },
  { district: "Coimbatore", constituency: "Valparai" },
  { district: "Coimbatore", constituency: "Sulur" },
  { district: "Coimbatore", constituency: "Coimbatore North" },
  { district: "Coimbatore", constituency: "Thondamuthur" },
  { district: "Coimbatore", constituency: "Coimbatore South" },
  { district: "Coimbatore", constituency: "Singanallur" },
  { district: "Coimbatore", constituency: "Kinathukadavu" },
  { district: "Coimbatore", constituency: "Kavundampalayam" },
  { district: "Coimbatore", constituency: "Mettupalayam" },
  // The Nilgiris
  { district: "The Nilgiris", constituency: "Gudalur" },
  { district: "The Nilgiris", constituency: "Udhagamandalam" },
  { district: "The Nilgiris", constituency: "Coonoor" },
  // Tiruvannamalai
  { district: "Tiruvannamalai", constituency: "Tiruvannamalai" },
  { district: "Tiruvannamalai", constituency: "Kilpennathur" },
  { district: "Tiruvannamalai", constituency: "Kalasapakkam" },
  { district: "Tiruvannamalai", constituency: "Polur" },
  { district: "Tiruvannamalai", constituency: "Arani" },
  { district: "Tiruvannamalai", constituency: "Cheyyar" },
  { district: "Tiruvannamalai", constituency: "Gingee" },
  // Villupuram
  { district: "Villupuram", constituency: "Tindivanam" },
  { district: "Villupuram", constituency: "Vanur" },
  { district: "Villupuram", constituency: "Villupuram" },
  { district: "Villupuram", constituency: "Vikravandi" },
  { district: "Villupuram", constituency: "Tirukoilur" },
  { district: "Villupuram", constituency: "Ulundurpet" },
  // Kallakurichi
  { district: "Kallakurichi", constituency: "Rishivandiyam" },
  { district: "Kallakurichi", constituency: "Sankarapuram" },
  { district: "Kallakurichi", constituency: "Kallakurichi" },
  { district: "Kallakurichi", constituency: "Chinnasalem" },
  // Cuddalore
  { district: "Cuddalore", constituency: "Vriddhachalam" },
  { district: "Cuddalore", constituency: "Neyveli" },
  { district: "Cuddalore", constituency: "Panruti" },
  { district: "Cuddalore", constituency: "Cuddalore" },
  { district: "Cuddalore", constituency: "Kurinjipadi" },
  { district: "Cuddalore", constituency: "Bhuvanagiri" },
  { district: "Cuddalore", constituency: "Chidambaram" },
  // Mayiladuthurai
  { district: "Mayiladuthurai", constituency: "Sirkazhi" },
  { district: "Mayiladuthurai", constituency: "Mayiladuthurai" },
  { district: "Mayiladuthurai", constituency: "Poompuhar" },
  { district: "Mayiladuthurai", constituency: "Tharangambadi" },
  // Nagapattinam
  { district: "Nagapattinam", constituency: "Nagapattinam" },
  { district: "Nagapattinam", constituency: "Kilvelur" },
  { district: "Nagapattinam", constituency: "Vedaranyam" },
  { district: "Nagapattinam", constituency: "Tirutturaipoondi" },
  // Tiruvarur
  { district: "Tiruvarur", constituency: "Tiruvarur" },
  { district: "Tiruvarur", constituency: "Papanasam" },
  { district: "Tiruvarur", constituency: "Thiruthuraipoondi" },
  { district: "Tiruvarur", constituency: "Mannargudi" },
  { district: "Tiruvarur", constituency: "Thiruvidaimarudur" },
  // Thanjavur
  { district: "Thanjavur", constituency: "Kumbakonam" },
  { district: "Thanjavur", constituency: "Papanasam" },
  { district: "Thanjavur", constituency: "Thanjavur" },
  { district: "Thanjavur", constituency: "Orathanadu" },
  { district: "Thanjavur", constituency: "Pattukkottai" },
  { district: "Thanjavur", constituency: "Peravurani" },
  { district: "Thanjavur", constituency: "Thiruvaiyaru" },
  // Pudukottai
  { district: "Pudukottai", constituency: "Aranthangi" },
  { district: "Pudukottai", constituency: "Karambakudi" },
  { district: "Pudukottai", constituency: "Alangudi" },
  { district: "Pudukottai", constituency: "Pudukottai" },
  { district: "Pudukottai", constituency: "Gandharvakottai" },
  { district: "Pudukottai", constituency: "Viralimalai" },
  // Tiruchirappalli
  { district: "Tiruchirappalli", constituency: "Manapparai" },
  { district: "Tiruchirappalli", constituency: "Srirangam" },
  { district: "Tiruchirappalli", constituency: "Tiruchirappalli West" },
  { district: "Tiruchirappalli", constituency: "Tiruchirappalli East" },
  { district: "Tiruchirappalli", constituency: "Thiruverumbur" },
  { district: "Tiruchirappalli", constituency: "Lalgudi" },
  { district: "Tiruchirappalli", constituency: "Manachanallur" },
  { district: "Tiruchirappalli", constituency: "Musiri" },
  // Karur
  { district: "Karur", constituency: "Kulithalai" },
  { district: "Karur", constituency: "Manapparai" },
  { district: "Karur", constituency: "Karur" },
  { district: "Karur", constituency: "Krishnarayapuram" },
  // Ariyalur
  { district: "Ariyalur", constituency: "Ariyalur" },
  { district: "Ariyalur", constituency: "Jayankondam" },
  { district: "Ariyalur", constituency: "Sendurai" },
  // Perambalur
  { district: "Perambalur", constituency: "Perambalur" },
  { district: "Perambalur", constituency: "Kunnam" },
  { district: "Perambalur", constituency: "Veppur" },
  // Dindigul
  { district: "Dindigul", constituency: "Palani" },
  { district: "Dindigul", constituency: "Oddanchatram" },
  { district: "Dindigul", constituency: "Athoor" },
  { district: "Dindigul", constituency: "Nilakottai" },
  { district: "Dindigul", constituency: "Natham" },
  { district: "Dindigul", constituency: "Dindigul" },
  // Theni
  { district: "Theni", constituency: "Bodinayakanur" },
  { district: "Theni", constituency: "Cumbum" },
  { district: "Theni", constituency: "Andipatti" },
  { district: "Theni", constituency: "Theni-Allinagaram" },
  // Madurai
  { district: "Madurai", constituency: "Sholavandan" },
  { district: "Madurai", constituency: "Usilampatti" },
  { district: "Madurai", constituency: "Melur" },
  { district: "Madurai", constituency: "Madurai East" },
  { district: "Madurai", constituency: "Madurai Central" },
  { district: "Madurai", constituency: "Madurai South" },
  { district: "Madurai", constituency: "Madurai North" },
  { district: "Madurai", constituency: "Madurai West" },
  { district: "Madurai", constituency: "Tirupparankundram" },
  // Sivaganga
  { district: "Sivaganga", constituency: "Manamadurai" },
  { district: "Sivaganga", constituency: "Sivaganga" },
  { district: "Sivaganga", constituency: "Karaikudi" },
  { district: "Sivaganga", constituency: "Tiruppattur" },
  { district: "Sivaganga", constituency: "Ilayankudi" },
  // Ramanathapuram
  { district: "Ramanathapuram", constituency: "Paramakudi" },
  { district: "Ramanathapuram", constituency: "Tiruvadanai" },
  { district: "Ramanathapuram", constituency: "Ramanathapuram" },
  { district: "Ramanathapuram", constituency: "Mudhukulathur" },
  { district: "Ramanathapuram", constituency: "Rameswaram" },
  // Virudhunagar
  { district: "Virudhunagar", constituency: "Aruppukkottai" },
  { district: "Virudhunagar", constituency: "Rajapalayam" },
  { district: "Virudhunagar", constituency: "Srivilliputhur" },
  { district: "Virudhunagar", constituency: "Virudhunagar" },
  { district: "Virudhunagar", constituency: "Sivakasi" },
  { district: "Virudhunagar", constituency: "Sattur" },
  // Tenkasi
  { district: "Tenkasi", constituency: "Alangulam" },
  { district: "Tenkasi", constituency: "Tenkasi" },
  { district: "Tenkasi", constituency: "Sankarankovil" },
  { district: "Tenkasi", constituency: "Kadayanallur" },
  // Tirunelveli
  { district: "Tirunelveli", constituency: "Ambasamudram" },
  { district: "Tirunelveli", constituency: "Palayamkottai" },
  { district: "Tirunelveli", constituency: "Nagarcoil" },
  { district: "Tirunelveli", constituency: "Tirunelveli" },
  { district: "Tirunelveli", constituency: "Tirunelveli City" },
  { district: "Tirunelveli", constituency: "Nanguneri" },
  { district: "Tirunelveli", constituency: "Radhapuram" },
  // Thoothukudi
  { district: "Thoothukudi", constituency: "Thoothukudi" },
  { district: "Thoothukudi", constituency: "Tiruchendur" },
  { district: "Thoothukudi", constituency: "Srivaikuntam" },
  { district: "Thoothukudi", constituency: "Ottapidaram" },
  { district: "Thoothukudi", constituency: "Vilathikulam" },
  // Kanyakumari
  { district: "Kanyakumari", constituency: "Padmanabhapuram" },
  { district: "Kanyakumari", constituency: "Vilavancode" },
  { district: "Kanyakumari", constituency: "Killiyoor" },
  { district: "Kanyakumari", constituency: "Nagercoil" },
  { district: "Kanyakumari", constituency: "Colachel" },
  { district: "Kanyakumari", constituency: "Thovalai" },
  { district: "Kanyakumari", constituency: "Kovalam" },
];

export const TN_DISTRICTS = [...new Set(TN_CONSTITUENCIES.map((c) => c.district))].sort();

export function getConstituenciesByDistrict(district: string): string[] {
  return TN_CONSTITUENCIES.filter((c) => c.district === district).map((c) => c.constituency);
}
